#ifndef __COLOR_H__
#define __COLOR_H__

#define COLOR_NONE  "\e[0m"
#define COLOR_BOLD  "\e[1m"
#define COLOR_UNDERLINE  "\e[4m"
#define COLOR_BLINK  "\e[5m"
#define COLOR_REVERSE  "\e[7m"
#define COLOR_HIDE  "\e[8m"
#define CLEAR  "\e[2J"

#define FONT_COLOR_BLACK "\e[0;30m"
#define FONT_COLOR_L_BLACK "\e[1;30m"
#define FONT_COLOR_RED "\e[0;31m"
#define FONT_COLOR_L_RED "\e[1;31m"
#define FONT_COLOR_GREEN "\e[0;32m"
#define FONT_COLOR_L_GREEN "\e[1;32m"
#define FONT_COLOR_BROWN "\e[0;33m"
#define FONT_COLOR_L_BROWN "\e[1;33m"
#define FONT_COLOR_BLUE "\e[0;34m"
#define FONT_COLOR_L_BLUE "\e[1;34m"
#define FONT_COLOR_PURPLE "\e[0;35m"
#define FONT_COLOR_L_PURPLE "\e[1;35m"
#define FONT_COLOR_CYAN "\e[0;36m"
#define FONT_COLOR_L_CYAN "\e[1;36m"
#define FONT_COLOR_GRAY "\e[0;37m"
#define FONT_COLOR_WHITE "\e[1;37m"

#define BACKGROUND_COLOR_BLACK "\e[0;40m"
#define BACKGROUND_COLOR_L_BLACK "\e[1;40m"
#define BACKGROUND_COLOR_RED "\e[0;41m"
#define BACKGROUND_COLOR_L_RED "\e[1;41m"
#define BACKGROUND_COLOR_GREEN "\e[0;42m"
#define BACKGROUND_COLOR_L_GREEN "\e[1;42m"
#define BACKGROUND_COLOR_BROWN "\e[0;43m"
#define BACKGROUND_COLOR_L_BROWN "\e[1;43m"
#define BACKGROUND_COLOR_BLUE "\e[0;44m"
#define BACKGROUND_COLOR_L_BLUE "\e[1;44m"
#define BACKGROUND_COLOR_PURPLE "\e[0;45m"
#define BACKGROUND_COLOR_L_PURPLE "\e[1;45m"
#define BACKGROUND_COLOR_CYAN "\e[0;46m"
#define BACKGROUND_COLOR_L_CYAN "\e[1;46m"
#define BACKGROUND_COLOR_GRAY "\e[0;47m"
#define BACKGROUND_COLOR_WHITE "\e[1;47m"


#endif
